# --- !Ups

create table "TEXTS" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "title" VARCHAR NOT NULL,
  "content" VARCHAR NOT NULL
);

create unique index "uniq_title" on "TEXTS" ("title");

# --- !Downs

DROP TABLE "TEXTS";
